version: "3"

services:
  frontend:
    build: ./frontend
    environment:
      - PUBLIC_SERVER_NAME=${SERVER_NAME}
      - PUBLIC_MODE=${MODE}
    depends_on:
      - nginx
      - backend

  backend:
    build: ./backend
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MODE=${MODE}
    depends_on:
      - nginx
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo_volume:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  nginx:
    build:
      context: ./nginx
      args:
        - MODE=${MODE}
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SERVER_NAME=$SERVER_NAME
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    restart: always

volumes:
  mongo_volume:
