version: "3"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENDPOINT=${ENDPOINT}
      - DATABASE=${DATABASE}
      - YDB_SERVICE_ACCOUNT_KEY_FILE_CREDENTIALS=${YDB_SERVICE_ACCOUNT_KEY_FILE_CREDENTIALS}
      - SECRET_KEY=secret
